/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      width: {
        default: '1440px',
      },
      keyframes: {
        floatY: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(30px)' },
        },
        floatX: {
          '0%, 100%': { transform: 'translateX(0px)' },
          '33%': { transform: 'translateX(-160px)' },
          '66%': { transform: 'translateX(160px)' },
        },
        floatLeft: {
          '0%, 100%': { transform: 'translateX(0%)' },
          '50%': { transform: 'translateX(-35%)' },
        },
      },
      animation: {
        floatY: 'floatY 3s ease-in-out infinite',
        floatX: 'floatX 60s ease-in-out infinite',
        floatLeft: 'floatLeft 40s ease-in-out infinite',
      },
      fontFamily: {
        tuffy: ['TUFFY'],
        acme: ['ACME'],
        inter: ['INTER'],
        truculenta: ['TRUCULENTA'],
        connection: ['CONNECTION'],
      },
      backgroundImage: {
        sun: "url('./images/sun.png')",
        grass: "url('./images/grass.svg')",
        grassBackdrop: "url('./images/grassBackdrop.svg')",
        connectwallet: "url('./images/buttons/connectWallet.svg')",
        scrollDown: "url('./images/buttons/scrollDown.svg')",
        backToTop: "url('./images/buttons/backToTop.svg')",
        cave: "url('./images/cave.png')",
        shroom: "url('./images/nftShroom.png')",
        mint: "url('./images/mint.png')",
        dirt: "url('./images/dirt.png')",
        centerIsland: "url('./images/islands/centerIsland.svg')",
        leftIsland: "url('./images/islands/leftIsland.svg')",
        rightIsland: "url('./images/islands/rightIsland.svg')",
        logo: "url('./images/logo.svg')",
        logo1: "url('./images/logo1.svg')",
        telegram: "url('./images/contacts/telegram.svg')",
        discord: "url('./images/contacts/discord.svg')",
        twitter: "url('./images/contacts/twitter.svg')",
        github: "url('./images/contacts/github.svg')",
        telegramWhite: "url('./images/contacts/telegramWhite.svg')",
        discordWhite: "url('./images/contacts/discordWhite.svg')",
        twitterWhite: "url('./images/contacts/twitterWhite.svg')",
        githubWhite: "url('./images/contacts/githubWhite.svg')",
        whitepaper: "url('./images/buttons/whitepaper.png')",
        chart: "url('./images/buttons/chart.png')",
        audit: "url('./images/buttons/audit.png')",
        presale: "url('./images/buttons/presale.png')",
        cards: "url('./images/cards.png')",
        alex: "url('./images/contacts/alex.png')",
        kaban: "url('./images/contacts/kaban.png')",
        email: "url('./images/contacts/email.svg')",
        stones: "url('./images/stones.png')",
        nightsky: "url('./images/nightsky.png')",
        moon: "url('./images/moon.png')",
        allies: "url('./images/islands/allies.png')",
        footerlogo: "url('./images/footerlogo.png')",

        // gradientRadial: 'radial-gradient(var(--tw-gradient-stops))',
        // grass: "url('./images/bg/grass.png')",
        // undergrass: "url('./images/bg/undergrass.png')",
        // sun: "url('./images/bg/sun.png')",
        // connectwallet: "url('./images/bg/connectwallet.png')",
        // kabanaclub: "url('./images/bg/kabanaclub.png')",
        // discord: "url('./images/contacts/discord.png')",
        // discordWhite: "url('./images/contacts/discordWhite.png')",
        // github: "url('./images/contacts/github.png')",
        // githubWhite: "url('./images/contacts/githubWhite.png')",
        // telegram: "url('./images/contacts/telegram.png')",
        // telegramWhite: "url('./images/contacts/telegramWhite.png')",
        // twitter: "url('./images/contacts/twitter.png')",
        // twitterWhite: "url('./images/contacts/twitterWhite.png')",
        // shroom: "url('./images/nftShroom.png')",
        // mint: "url('./images/bg/mint.png')",
        // cave: "url('./images/cave.png')",
        // cards: "url('./images/bg/cards.png')",
        // logo: "url('./images/logo.png')",
        // dirt1: "url('./images/bg/dirt1.png')",
        // dirt2: "url('./images/bg/dirt2.png')",
        // dirt3: "url('./images/bg/dirt3.png')",
        // dirt4: "url('./images/bg/dirt4.png')",
        // dirt5: "url('./images/bg/dirt5.png')",
        // stones: "url('./images/bg/stones.png')",
        // alex: "url('./images/team/alex.png')",
        // kaban: "url('./images/team/kaban.png')",
        // teamTelegram: "url('./images/team/telegram.png')",
        // teamTiktok: "url('./images/team/tiktok.png')",
        // teamTwitter: "url('./images/team/twitter.png')",
        // teamEmail: "url('./images/team/mail.png')",
      },
      colors: {
        sky: '#40DDFF',
        alexGradient: '#00A3FF',
        kabanGradient: '#FF0000',
        footer: '#000E24',
      },
    },
  },
  plugins: [
    require('tailwindcss-animation-delay'),
    require('tailwindcss-textshadow'),
    require('tailwindcss-text-fill-stroke'),
  ],
};
